#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.


version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      #- echo Nothing to do in the pre_build phase...
      - cd api/
      - mvn -B verify --file pom.xml
  build:
    commands:
      - echo Build started on `date`
      - echo Path is `pwd`
      - cd ..
      - echo Path is now `pwd` ?????
      - cd api/
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - api/target/webApp.war